### ISSUE TITLE
Repo's linked site is invalid

### ISSUE THREAD

**Issue by cadecuddy** [jonathan-lor/my-site#1]
The linked site for the repo:
![image](https://github.com/user-attachments/assets/42078fb9-cd6e-418b-84db-b982d89a32c2)

doesn't go to the [actual site](https://www.jonathanlor.com/).

This is what happens when you try to visit the linked repo site:
![image](https://github.com/user-attachments/assets/890b69a9-c556-43e3-a239-073dba4b8810)

**Comment by jonathan-lor** [comment]
resolved.
